Ext.define('Poise.view.OptionsView', {
    extend: 'Ext.Container',

    config: {
        tpl: Ext.create('Ext.XTemplate',
            '<tpl for=".">',
                '<div class="table-header"><i class="fa fa-life-ring"></i> {title}</div>',
                '<table class="table table-bordered table-responsive">',
                    '<thead>',
                        '<th>Operation</th>',
                        '<th>Operator(s)</th>',
                        '<th>Recent Output</th>',
                    '</thead>',
                    '<tpl for="options">',
                        '<tr class="x-list-item dynamic-options">',
                            '<td>{operation}</td>',
                            '<td class="no-padding">',
                                '<tpl for="operator">',
                                    '<div>',
                                        '<span class="op-boxed {name_class}">{name}</span>',
                                        '<span class="op-boxed {skill_class}">{skill}</span>',
                                    '</div>',
                                '</tpl>',
                            '</td>',
                            '<tpl if="output &gt; 60 || output == 60">',
                                '<td class="no-padding">',
                                    '<span class="boxed green-item">{output}</span>',
                                    '<span class="boxed green-item">{output}</span>',
                                    '<span class="boxed green-item">{output}</span>',
                                '</td>',
                            '</tpl>',
                            '<tpl if="output &lt; 60">',
                                '<td class="no-padding">',
                                    '<div class="boxed red-item">{output}</div>',
                                    '<div class="boxed red-item">{output}</div>',
                                    '<div class="boxed red-item">{output}</div>',
                                '</td>',
                            '</tpl>',
                        '</tr>',
                    '</tpl>',
                    '<tpl if="options.length == 0">',
                        '<tr><td colspan="2"><i>No Options Available</i></td></tr>',
                    '</tpl>',
                '</table>',
            '</tpl>'
        )
    }
});